### ISSUE TITLE
Why Metal/Why lock to apple devices only?

### ISSUE THREAD

**Issue by VioletasTheThird** [untoldengine/UntoldEngine#115]
The engine truely looks great, and I would love to be able to use something like this. However, I am quite puzzled about why it is specifically for MacOS, iOS, etc, just apple devices. It seems like it is needlessly locking the engine to a platform, and given that both in the desktop and mobile space Apple hasn't even got nearly as much market share as their competitors, it seems to be locking away potential users who would want to target these competing platforms.

**Comment by untoldengine** [comment]
Hi @VioletasTheThird 

That’s a really good question. 

I started the development of the engine using OpenGL and Xcode. However, I decided to port the engine to Metal once I saw an Augmented Reality demo. I realized that Augmented Reality (AR) is the future of gaming and that it may be a good idea to have this feature available in the engine. However, the AR framework only works with the Metal API; it does not support OpenGL. 

That was the push that I needed to port the engine to Metal. Before this time, I was hesitant to port it, since it would require a lot of work. Luckily, it was easier than I thought. The Metal API is way less convoluted than OpenGL and a lot easier to work with. I’m actually happy that I did the porting. Metal is really easy to understand. 

I also like the fact that Metal is cross-platform. Your game will work on any Apple device without any extra work. It makes game dev a lot cleaner and you don’t have to worry if your game looks good on other devices. 

Moreover, in the beginning I was not planning to release the engine to the public. It was more of an educational hobby of mine. However, as the engine improved I decided to release it as an Open Source. You can say that things that just sort of happened along the way and I decided to keep the engine to work on Apple devices. There was no business intent since the beginning, only a desire to learn.

Thanks
Harold

**Comment by VioletasTheThird** [comment]
Ah ok, fair enough. Thank you for the detailed answer, and I wish you the best of luck going forward!
